[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
custom_spl_tokens = "GmWEsdzWFfkpMtRKnkEMcC17NvqepxktLL9XEQwMKZTP"
stake_tokens = "7a8fBQMwbtE1C61fcGUW6quAgdqdmzYojha5cQq9Ju4q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
closeProgram = "bun run ./scripts/closeProgram.ts"
createAndMintToken = "bun run ./scripts/deployAndMintToken.ts"
initializePool = "bun run ./scripts/initializePool.ts"
migrateTypesToClient = "./scripts/generateTypes.sh"
temp = "bun run ./scripts/temp.ts"
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
transferTokens = "bun run ./scripts/transferTokens.ts"
fundPool = "bun run ./scripts/fundPool.ts"
mintTokens = "bun run ./scripts/mintTokens.ts"
deploy = "bun run ./scripts/deployProgram.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
